@extends('errors.layout')
@section('title', 'Halaman Tidak Ditemukan')
@section('code', '404')
@section('heading', 'Halaman yang Anda cari tidak ditemukan')
@section('message', 'Tautan mungkin sudah berubah, tidak lagi tersedia, atau alamatnya kurang tepat. Mari kembali ke halaman utama NIVICO.')
